### PR TITLE
Conversion to Portable Library

### PR DESCRIPTION
**Pull request by ibebbs**
Colourful has been converted to a portable class library (PCL) compatible with Win45, Windows Phone 8 and Windows Store Apps 8.1 (should be compatible with Windows 10 / UWP once tooling is available). A .NET45 specific library is included to include feature parity (converting from System.Drawing.Color) but does not include implicit operators and therefore includes breaking changes. Compatibility with Framework 3.5 is not maintained at the moment but should be possible if required.
FAKE based build / packaging script employed to provide compatibility with online build systems (i.e. MyGet) and construct / package libraries for multiple platforms.

### CODE REVIEW

**Comment by tompazourek** [comment]
Hi, thanks for the efforts. I am looking forward to integrating this. The pull-request cannot be merged right now (I suspect it's because you did not merge this commit: https://github.com/tompazourek/Colourful/commit/8088b181dcf09877d103b6c06bf38949bde02170).

I like the adjusted project structure and I have to learn a bit more about FAKE scripts, but it seems that it'll be possible to build and package the artifacts this way. I will need some time to integrate it with the build system currently used (AppVeyor) and also maybe make some small adjustments and tweaks until it can be merged into master and deployed to NuGet.

Because of this, I **took your changes and put them in a new branch called [portable-library](https://github.com/tompazourek/Colourful/tree/portable-library)** where I will continue integrating and soon merge it to the master.

Thanks!

**Comment by ibebbs** [comment]
No problem. Let me know if I can do anything to make the merge easier.

**Comment by tompazourek** [comment]
I decided to change the stuff around a bit and create PCL as one of many build configurations. Currently there are configurations for .NET 3.5, .NET 4.0, .NET 4.5 and PCL.

Could you please check if [the current build artifacts](https://ci.appveyor.com/project/tompazourek/colourful/build/artifacts) are ok? I don't have much experience with PCLs and using them, from what I discovered using dotPeek and simple experiments in Visual Studio, it seemed fine.

If you have some feedback with regards to the FAKE script I modified and the compatibility with MyGet, I would be glad to hear it. However, I tried to modify the scripts so it would work in a similar fashion as in your branch, so I hope there shouldn't be an issue with that.

If everything is ok, I will merge [portable-library](https://github.com/tompazourek/Colourful/tree/portable-library) to [master](https://github.com/tompazourek/Colourful/tree/master) and then release version 1.1.0 to NuGet.

**Comment by ibebbs** [comment]
Hi Tom,

All looks good to me!

I installed your package into a solution containing Win45, Win8.1 and WinPhone8.1 projects and it compiled fine.

I like the neatness of the single project cross compiled into the various platforms assemblies, although I must say I've never been a big fan of compiler directives nor manually editing project files to provide the appropriate configurations.

I like what you've done with the FAKE build script. Should build fine in MyGet.

Thanks for pulling it all in so quickly, will be nice to be able to revert to a Nuget hosted package once its merged into master and released.

Cheers,
  Ian

**Comment by tompazourek** [comment]
Thanks for the feedback, Ian. I merged the branches and released [version 1.1.0 to NuGet](https://www.nuget.org/packages/Colourful/1.1.0).

**Pull request closed without merging**
